// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB360lUdEfZ2gDi98TDQH2879DgbmFVu_8',
    appId: '1:210548096618:web:0018324b6e95a3d6995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    authDomain: 'flutter-firebase-auth-c6d6c.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    measurementId: 'G-HPTD71VZ0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIBFrp92jbK3PT90NO_t8-Jg8hM_4G7D4',
    appId: '1:210548096618:android:4d6f4266b43f5cd8995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAwjC4OCmd4QttXtV1gxbN9SQc1hZHyBM',
    appId: '1:210548096618:ios:f17a647c0c69e741995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    androidClientId: '210548096618-9vvpbi1vc001ddcopjkdvok6vk7q70qi.apps.googleusercontent.com',
    iosClientId: '210548096618-vppet7an7ge0hagmm4dv7k4g498uetpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sociallearnapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAwjC4OCmd4QttXtV1gxbN9SQc1hZHyBM',
    appId: '1:210548096618:ios:f17a647c0c69e741995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    androidClientId: '210548096618-9vvpbi1vc001ddcopjkdvok6vk7q70qi.apps.googleusercontent.com',
    iosClientId: '210548096618-vppet7an7ge0hagmm4dv7k4g498uetpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sociallearnapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB360lUdEfZ2gDi98TDQH2879DgbmFVu_8',
    appId: '1:210548096618:web:02161bd2254dd0c8995413',
    messagingSenderId: '210548096618',
    projectId: 'flutter-firebase-auth-c6d6c',
    authDomain: 'flutter-firebase-auth-c6d6c.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-c6d6c.firebasestorage.app',
    measurementId: 'G-4G47R535SE',
  );
}
